name: DotNet CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: DotNet Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.607'
      - name: Setup dotnet
        uses: casz/setup-dotnet@fix/dotnet-global-tool
        with:
          dotnet-version: '3.1.100'

      # workaround for using multiple dotnet core installs
      - name: .net SxS
        run: rsync -a ${DOTNET_ROOT/3.1.100/2.1.607}/* $DOTNET_ROOT/

      - run: dotnet tool install -g Codecov.Tool
        shell: pwsh

      - run: dotnet tool install -g GitVersion.Tool
        shell: pwsh

      - run: dotnet gitversion /l console /output buildserver
        shell: pwsh

      - run: ./build.ps1
        shell: pwsh

      - run: ./test.ps1
        shell: pwsh
